(function(root,factory){const data=factory();if(typeof module==="object"&&module.exports)module.exports=data;root.StackDoctorCatalog=data})(typeof globalThis!=="undefined"?globalThis:this,function(){return {asOf:"2026-09-28",models:[
{id:"gpt-6-astra",provider:"OpenAI",name:"GPT-6 Astra",tier:"frontier",tasks:["coding","research","analysis","automation"],context:"maximum",quality:5,speed:2,modalities:["text","image"],input:10,output:50,plan:"API pay-as-you-go",mode:"medium by default; raise to high/xhigh/max only when the task earns it",link:"https://developers.openai.com/api/docs/models",source:"https://platform.openai.com/docs/pricing"},
{id:"gpt-6-sol",provider:"OpenAI",name:"GPT-6 Sol",tier:"balanced",tasks:["writing","coding","research","analysis","automation"],context:"large",quality:4,speed:4,modalities:["text","image"],input:2,output:10,plan:"API pay-as-you-go",mode:"medium for standard work; high for difficult review",link:"https://developers.openai.com/api/docs/models",source:"https://platform.openai.com/docs/pricing"},
{id:"gpt-6-luna",provider:"OpenAI",name:"GPT-6 Luna",tier:"economy",tasks:["writing","coding","automation"],context:"large",quality:3,speed:5,modalities:["text","image"],input:.1,output:.5,plan:"API pay-as-you-go",mode:"low/medium; escalate uncertain cases",link:"https://developers.openai.com/api/docs/models",source:"https://platform.openai.com/docs/pricing"},
{id:"claude-fable-5-1",provider:"Anthropic",name:"Claude Fable 5.1",tier:"frontier",tasks:["coding","research","analysis","automation"],context:"maximum",quality:5,speed:2,modalities:["text","image"],input:10,output:50,plan:"Claude API pay-as-you-go",mode:"adaptive reasoning; reserve for long-horizon work",link:"https://docs.anthropic.com/en/docs/about-claude/models/overview",source:"https://docs.anthropic.com/en/docs/about-claude/models/overview"},
{id:"claude-opus-5-5",provider:"Anthropic",name:"Claude Opus 5.5",tier:"frontier",tasks:["writing","coding","research","analysis"],context:"maximum",quality:5,speed:3,modalities:["text","image"],input:4,output:20,plan:"Claude API pay-as-you-go",mode:"adaptive reasoning; use for careful judgment",link:"https://docs.anthropic.com/en/docs/about-claude/models/overview",source:"https://docs.anthropic.com/en/docs/about-claude/models/overview"},
{id:"claude-sonnet-5-5",provider:"Anthropic",name:"Claude Sonnet 5.5",tier:"balanced",tasks:["writing","coding","research","analysis","automation"],context:"maximum",quality:4,speed:5,modalities:["text","image"],input:2,output:10,plan:"Claude API pay-as-you-go",mode:"lower effort for fast iteration; raise effort only when needed",link:"https://www.anthropic.com/claude-sonnet-5-5",source:"https://www.anthropic.com/claude-sonnet-5-5"},
{id:"claude-haiku-4-5",provider:"Anthropic",name:"Claude Haiku 4.5",tier:"economy",tasks:["writing","coding","automation"],context:"large",quality:3,speed:5,modalities:["text","image"],input:1,output:5,plan:"Claude API pay-as-you-go",mode:"fast bounded work; escalate low-confidence cases",link:"https://docs.anthropic.com/en/docs/about-claude/models/overview",source:"https://docs.anthropic.com/en/docs/about-claude/models/overview"},
{id:"gemini-3-8-flash",provider:"Google",name:"Gemini 3.8 Flash",tier:"balanced",tasks:["writing","coding","research","analysis","automation","media"],context:"maximum",quality:4,speed:5,modalities:["text","image","audio","video"],input:.75,output:3.75,plan:"Gemini API Paid",mode:"standard; batch when latency is flexible",link:"https://aistudio.google.com/",source:"https://ai.google.dev/gemini-api/docs/pricing",note:"Promotional API price through 2026-12-31"},
{id:"gemini-3-5-flash",provider:"Google",name:"Gemini 3.5 Flash",tier:"balanced",tasks:["writing","research","automation","media"],context:"large",quality:3,speed:5,modalities:["text","image","audio","video"],input:1.5,output:9,plan:"Gemini API Paid",mode:"standard or batch",link:"https://aistudio.google.com/",source:"https://ai.google.dev/gemini-api/docs/pricing"},
{id:"gemini-3-5-flash-lite",provider:"Google",name:"Gemini 3.5 Flash-Lite",tier:"economy",tasks:["writing","automation","media"],context:"large",quality:3,speed:5,modalities:["text","image","audio","video"],input:.3,output:2.5,plan:"Gemini API Paid",mode:"standard; ideal for high-volume bounded work",link:"https://aistudio.google.com/",source:"https://ai.google.dev/gemini-api/docs/pricing"},
{id:"grok-4-7",provider:"xAI",name:"Grok 4.7",tier:"frontier",tasks:["writing","coding","research","analysis","automation"],context:"large",quality:5,speed:4,modalities:["text"],input:2,output:6,plan:"xAI API pay-as-you-go",mode:"configurable reasoning",link:"https://console.x.ai/",source:"https://docs.x.ai/docs/models"},
{id:"openrouter-auto",provider:"OpenRouter",name:"Auto Router",tier:"router",tasks:["writing","coding","research","analysis","automation","media"],context:"maximum",quality:4,speed:4,modalities:["text","image"],input:null,output:null,plan:"OpenRouter pay-as-you-go",mode:"automatic routing; verify selected model and price",link:"https://openrouter.ai/models",source:"https://openrouter.ai/models",note:"Price varies with the routed model"},
{id:"qwen3-8b-local",provider:"Local / Ollama",name:"Qwen3 8B",tier:"local",tasks:["writing","coding","automation"],context:"medium",quality:2,speed:4,modalities:["text"],input:0,output:0,plan:"Free local via Ollama",mode:"local thinking/tools; hardware and energy not included",link:"https://ollama.com/library/qwen3",source:"https://ollama.com/library"},
{id:"gpt-oss-20b-local",provider:"Local / Ollama",name:"gpt-oss 20B",tier:"local",tasks:["coding","analysis","automation"],context:"large",quality:3,speed:3,modalities:["text"],input:0,output:0,plan:"Free local via Ollama",mode:"local reasoning/tools; hardware and energy not included",link:"https://ollama.com/library/gpt-oss",source:"https://ollama.com/library"},
{id:"gemma3-4b-local",provider:"Local / Ollama",name:"Gemma 3 4B",tier:"local",tasks:["writing","automation","media"],context:"medium",quality:2,speed:5,modalities:["text","image"],input:0,output:0,plan:"Free local via Ollama",mode:"fast local work; hardware and energy not included",link:"https://ollama.com/library/gemma3",source:"https://ollama.com/library"}
]}});
