import { mkdir, readdir, rm, writeFile } from "node:fs/promises";

const tabs = await fetch("http://127.0.0.1:9223/json/list").then(r => r.json());
const tab = tabs.find(x => x.type === "page");
if (!tab) throw new Error("No Chrome page target");
const ws = new WebSocket(tab.webSocketDebuggerUrl);
let id = 0;
const pending = new Map();
ws.onmessage = event => {
  const msg = JSON.parse(event.data);
  if (msg.id && pending.has(msg.id)) {
    const { resolve, reject } = pending.get(msg.id); pending.delete(msg.id);
    msg.error ? reject(new Error(msg.error.message)) : resolve(msg.result);
  }
};
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
const send = (method, params = {}) => new Promise((resolve, reject) => {
  const callId = ++id; pending.set(callId, { resolve, reject });
  ws.send(JSON.stringify({ id: callId, method, params }));
});
await send("Page.enable");
await send("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 2, mobile: true });
const downloadPath = "/tmp/stack-doctor-download-test";
await rm(downloadPath, { recursive: true, force: true });
await mkdir(downloadPath, { recursive: true });
await send("Page.setDownloadBehavior", { behavior: "allow", downloadPath });
const targetUrl = process.env.STACK_DOCTOR_URL || "http://127.0.0.1:4173/stack-doctor/";
await send("Page.navigate", { url: targetUrl });
await new Promise(r => setTimeout(r, 1000));
const landingShot = await send("Page.captureScreenshot", { format: "png", captureBeyondViewport: false });
await writeFile("/tmp/stack-doctor-mobile-landing.png", Buffer.from(landingShot.data, "base64"));
const expression = `(() => {
  const q=s=>document.querySelector(s);
  const set=(el,value)=>{el.value=value;el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));};
  q('#start-button').click();
  q('[name=role]').value='team'; q('[name=goal]').value='Reduce costs'; q('[name=pain]').value='Too many overlapping tools'; q('#next-button').click();
  q('[name=repeatHours]').value='12'; q('[name=projectCount]').value='8'; q('[name=overlap][value=yes]').checked=true; q('[name=primary][value=no]').checked=true; q('#next-button').click();
  q('#back-button').click(); q('#add-inventory').click();
  set(q('.inventory-row [data-key=provider]'),'Anthropic'); set(q('.inventory-row [data-key=modelId]'),'claude-sonnet-5-5'); set(q('.inventory-row [data-key=planId]'),'anthropic-pro'); set(q('.inventory-row [data-key=usage]'),'unused'); set(q('.inventory-row [data-key=purpose]'),'writing');
  const inventoryControlTypes=[...q('.inventory-row').querySelectorAll('[data-key]')].map(x=>x.tagName);
  const catalogPrice=q('.catalog-price').textContent;
  const inventoryOverflow=[...q('.inventory-row').querySelectorAll('*')].some(el=>el.getBoundingClientRect().right>innerWidth+1);
  q('#add-agent-component').click();
  set(q('.agent-component-row [data-agent-key=category]'),'template');
  set(q('.agent-component-row [data-agent-key=name]'),'Community template');
  set(q('.agent-component-row [data-agent-key=usage]'),'unused');
  set(q('.agent-component-row [data-agent-key=provenance]'),'unknown');
  set(q('.agent-component-row [data-agent-key=access]'),'admin');
  set(q('.agent-component-row [data-agent-key=persistence]'),'durable');
  set(q('.agent-component-row [data-agent-key=approval]'),'none');
  set(q('.agent-component-row [data-agent-key=audit]'),'none');
  set(q('.agent-component-row [data-agent-key=recovery]'),'none');
  set(q('.agent-component-row [data-agent-key=external]'),'yes');
  set(q('.agent-component-row [data-agent-key=overlap]'),'yes');
  q('#agent-footprint-export').click();
  q('#inventory-export').click(); q('#next-button').click();
  q('[name=taskTypes][value=research]').checked=true; q('[name=taskTypes][value=automation]').checked=true; q('[name=workflowName]').value='Weekly market intelligence'; q('[name=quality]').value='5'; q('[name=costSensitivity]').value='5'; q('[name=privacyPriority]').value='5'; q('[name=failureTolerance]').value='5'; q('[name=contextSize]').value='large'; q('[name=outputSize]').value='large'; q('[name=reasoningDepth]').value='frontier'; q('[name=runsPerMonth]').value='12'; q('[name=budgetCap]').value='150'; q('[name=capabilities][value=local]').checked=true; q('#next-button').click();
  q('[name=sensitive][value=customer]').checked=true; q('[name=sensitive][value=credentials]').checked=true; q('[name=privacyReview][value=no]').checked=true; q('[name=exports][value=no]').checked=true; q('#next-button').click();
  q('[name=renewals][value=no]').checked=true; q('[name=automation][value=no]').checked=true; q('[name=humanReview][value=no]').checked=true; q('.consent input').checked=true; q('#doctor-form').requestSubmit();
  q('#download-button').click();
  const externalRequests = performance.getEntriesByType('resource').map(x=>x.name).filter(x=>!x.startsWith(location.origin));
  const overflowing = [...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect(); return r.right > innerWidth + 1 || r.left < -1}).map(el=>({tag:el.tagName,id:el.id,class:el.className,right:Math.round(el.getBoundingClientRect().right)})).slice(0,10);
  const modelLinks=[...q('#model-grid').querySelectorAll('a')].map(a=>a.href);
  return { resultsVisible: !q('#results').classList.contains('hidden'), score:q('#score').textContent, savings:q('#savings').textContent, decisions:q('#decision-grid').children.length, models:q('#model-grid').children.length, scoreBars:q('#model-grid').querySelectorAll('.score-bar').length, prescriptions:q('#prescription-grid').children.length, correctionLink:q('.methodology-links a').href, methodology:q('.methodology').textContent, modelLinks, freshness:q('#catalog-freshness').textContent, inventory:q('#inventory-summary').children.length, agentInventory:q('#agent-footprint-summary').children.length, agentFindings:q('#agent-risk-grid').children.length, agentScore:q('#agent-footprint-score').textContent, profiles:q('#workload-summary').children.length, typedInventoryFields:q('#inventory-rows').querySelectorAll('input:not([type=file]),textarea').length, typedAgentFields:q('#agent-footprint-rows').querySelectorAll('input,textarea').length, inventoryControlTypes,catalogPrice,inventoryOverflow,actions:q('#actions').children.length, warnings:q('#warnings').children.length, errors:q('#form-error').textContent, externalRequests, viewport:[innerWidth,innerHeight], scrollWidth:document.documentElement.scrollWidth, overflowing };
})()`;
const result = await send("Runtime.evaluate", { expression, returnByValue: true });
const value = result.result.value;
const resultsShot = await send("Page.captureScreenshot", { format: "png", captureBeyondViewport: true });
await writeFile("/tmp/stack-doctor-mobile-results.png", Buffer.from(resultsShot.data, "base64"));
await new Promise(r => setTimeout(r, 500));
const downloads = await readdir(downloadPath);
if (!value.resultsVisible || value.decisions < 3 || value.models < 3 || value.scoreBars !== value.models*3 || value.prescriptions !== 4 || !value.correctionLink.startsWith('mailto:') || !/Work Fit/.test(value.methodology) || value.modelLinks.some(x=>!x.startsWith('https://') || /utm_|ref=|affiliate/i.test(x)) || !/2026-09-28/.test(value.freshness) || value.inventory !== 1 || value.agentInventory !== 1 || value.agentFindings < 8 || !/Control score/.test(value.agentScore) || value.profiles < 3 || value.typedInventoryFields !== 0 || value.typedAgentFields !== 0 || value.inventoryControlTypes.some(x=>x!=="SELECT") || !value.catalogPrice.includes("$20.00/month") || value.inventoryOverflow || value.actions < 1 || value.warnings < 1 || value.errors || value.externalRequests.length || value.scrollWidth > value.viewport[0] || !downloads.includes("ai-stack-doctor-report.html") || !downloads.includes("ai-stack-inventory.json") || !downloads.includes("ai-stack-doctor-agent-footprint.json")) throw new Error(`Browser flow failed: ${JSON.stringify({value,downloads})}`);
console.log(`PASS: browser assessment flow ${JSON.stringify(value)}`);
console.log(`PASS: report download ${downloads.join(",")}`);
ws.close();
